# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: something
  pool: 5
  username: postgres
  password: admin

test:
  adapter: postgresql
  encoding: unicode
  database: something_test
  pool: 5
  username: postgres
  password: admin

amazon:
  service: S3
  access_key_id: ""
  secret_access_key: ""
  bucket: ""
  region: "us-east-1"
